# Generated by Django 5.0.2 on 2024-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='email@prueba.com', max_length=254),
        ),
    ]
