# Generated by Django 5.0.2 on 2024-02-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_author',
            field=models.CharField(max_length=30),
        ),
    ]
