# Generated by Django 5.0.2 on 2024-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='blog.category', verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog/files/blog_images', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_author',
            field=models.CharField(max_length=30, verbose_name='autor'),
        ),
    ]
