# Generated by Django 5.0.2 on 2024-03-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
